### PR TITLE
Animating sprite

### LINKED ISSUE #2: Animate character
Walking animation

### PR DESCRIPTION
**Pull request by hpx7**
Fixes #2

### CODE REVIEW

**Comment by hpx7** [comment]
Recording_2022-07-31_at_09 59 26

**Comment by hpx7** [comment]
@jyoung4242 one issue I see is that this won't work for other players, only the local user. So while the local user animates, all other players on the server will always have the idle animation.

I think we'll need to move the animation triggering logic to `updatePlayer` instead

**Comment by hpx7** [comment]
As a reference, you can see how I did it in a previous game: https://github.com/hathora/star-jump/blob/73e23cd110d2bc70154a568073aea987a401775c/client/web/src/scenes/game.ts#L233-L263

**Comment by jyoung4242** [comment]
i updated and pushed on animate-sprite a working update on UpdatePlayer

**Pull request merged**
